// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Mason

import 'package:go_router/go_router.dart';
import 'package:pos_manager/features/init/presentation/routes/init_route.dart' as init_route;

final List<RouteBase> allRoutes = [
  ...init_route.$appRoutes,
];
